version: "3"
services:
  influxdb_v2:
    image: quay.io/influxdb/influxdb:v2.0.4
    ports:
      - "8086:8086"
    environment:
      - INFLUXD_HTTP_BIND_ADDRESS=:8086
    command: influxd --reporting-disabled

  iot_center:
    image: node:12
    ports:
      - "5000:5000"
    environment:
      - INFLUX_URL=http://influxdb_v2:8086
    volumes:
      - $PWD/app:/app
    working_dir: /app
    command: ./run.sh
    depends_on:
      - influxdb_v2
